### ISSUE TITLE
Contact date out of chronological order.

### ISSUE THREAD

**Issue by jrprill** [cjdhein/sidekick#1]
![image](https://user-images.githubusercontent.com/45523284/49333584-efa83080-f586-11e8-9f5e-c22e3e724892.png)

After sorting by date, the contact history is not in correct order.
![image](https://user-images.githubusercontent.com/45523284/49333593-1ebea200-f587-11e8-86f5-5de7a2e375d7.png)

This occasionally happens before sorting as well.

**Comment by cjdhein** [comment]
Looking into https://datatables.net/blog/2014-12-18

**Comment by cjdhein** [comment]
Resolved by using moment.js to automatically recognize the date string as a date and enable proper sorting.
